#############################################################################
# Makefile for building: Qbiblio
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Mar 10 11:37:08 2016
# Project:  Qbiblio.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Qbiblio.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -IView -IModel -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Model/biblio.cpp \
		Model/cd.cpp \
		Model/dvd.cpp \
		Model/film.cpp \
		Model/libraryitem.cpp \
		Model/libro.cpp \
		Model/smartptr.cpp \
		Model/vhs.cpp \
		View/gestione_cd.cpp \
		View/gestione_dvd.cpp \
		View/gestione_libro.cpp \
		View/gestione_vhs.cpp \
		View/mywidget.cpp \
		View/trova_elemento.cpp moc_gestione_cd.cpp \
		moc_gestione_dvd.cpp \
		moc_gestione_libro.cpp \
		moc_gestione_vhs.cpp \
		moc_mywidget.cpp \
		moc_trova_elemento.cpp
OBJECTS       = main.o \
		biblio.o \
		cd.o \
		dvd.o \
		film.o \
		libraryitem.o \
		libro.o \
		smartptr.o \
		vhs.o \
		gestione_cd.o \
		gestione_dvd.o \
		gestione_libro.o \
		gestione_vhs.o \
		mywidget.o \
		trova_elemento.o \
		moc_gestione_cd.o \
		moc_gestione_dvd.o \
		moc_gestione_libro.o \
		moc_gestione_vhs.o \
		moc_mywidget.o \
		moc_trova_elemento.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Qbiblio.pro
QMAKE_TARGET  = Qbiblio
DESTDIR       = 
TARGET        = Qbiblio

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qbiblio.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Qbiblio.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -o Makefile Qbiblio.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Qbiblio1.0.0 || $(MKDIR) .tmp/Qbiblio1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qbiblio1.0.0/ && $(COPY_FILE) --parents Model/biblio.h Model/cd.h Model/container.h Model/dvd.h Model/film.h Model/libraryitem.h Model/libro.h Model/smartptr.h Model/vhs.h View/gestione_cd.h View/gestione_dvd.h View/gestione_libro.h View/gestione_vhs.h View/mywidget.h View/trova_elemento.h .tmp/Qbiblio1.0.0/ && $(COPY_FILE) --parents main.cpp Model/biblio.cpp Model/cd.cpp Model/dvd.cpp Model/film.cpp Model/libraryitem.cpp Model/libro.cpp Model/smartptr.cpp Model/vhs.cpp View/gestione_cd.cpp View/gestione_dvd.cpp View/gestione_libro.cpp View/gestione_vhs.cpp View/mywidget.cpp View/trova_elemento.cpp .tmp/Qbiblio1.0.0/ && (cd `dirname .tmp/Qbiblio1.0.0` && $(TAR) Qbiblio1.0.0.tar Qbiblio1.0.0 && $(COMPRESS) Qbiblio1.0.0.tar) && $(MOVE) `dirname .tmp/Qbiblio1.0.0`/Qbiblio1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qbiblio1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_gestione_cd.cpp moc_gestione_dvd.cpp moc_gestione_libro.cpp moc_gestione_vhs.cpp moc_mywidget.cpp moc_trova_elemento.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gestione_cd.cpp moc_gestione_dvd.cpp moc_gestione_libro.cpp moc_gestione_vhs.cpp moc_mywidget.cpp moc_trova_elemento.cpp
moc_gestione_cd.cpp: Model/libraryitem.h \
		Model/cd.h \
		View/gestione_cd.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) View/gestione_cd.h -o moc_gestione_cd.cpp

moc_gestione_dvd.cpp: Model/libraryitem.h \
		Model/dvd.h \
		Model/film.h \
		View/gestione_dvd.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) View/gestione_dvd.h -o moc_gestione_dvd.cpp

moc_gestione_libro.cpp: Model/libraryitem.h \
		Model/libro.h \
		View/gestione_libro.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) View/gestione_libro.h -o moc_gestione_libro.cpp

moc_gestione_vhs.cpp: Model/libraryitem.h \
		Model/vhs.h \
		Model/film.h \
		View/gestione_vhs.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) View/gestione_vhs.h -o moc_gestione_vhs.cpp

moc_mywidget.cpp: Model/biblio.h \
		Model/container.h \
		Model/smartptr.h \
		Model/libraryitem.h \
		Model/cd.h \
		Model/dvd.h \
		Model/film.h \
		Model/libro.h \
		Model/vhs.h \
		View/gestione_libro.h \
		View/gestione_cd.h \
		View/gestione_dvd.h \
		View/gestione_vhs.h \
		View/trova_elemento.h \
		View/mywidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) View/mywidget.h -o moc_mywidget.cpp

moc_trova_elemento.cpp: Model/biblio.h \
		Model/container.h \
		Model/smartptr.h \
		Model/libraryitem.h \
		Model/cd.h \
		Model/dvd.h \
		Model/film.h \
		Model/libro.h \
		Model/vhs.h \
		View/trova_elemento.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) View/trova_elemento.h -o moc_trova_elemento.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp View/mywidget.h \
		Model/biblio.h \
		Model/container.h \
		Model/smartptr.h \
		Model/libraryitem.h \
		Model/cd.h \
		Model/dvd.h \
		Model/film.h \
		Model/libro.h \
		Model/vhs.h \
		View/gestione_libro.h \
		View/gestione_cd.h \
		View/gestione_dvd.h \
		View/gestione_vhs.h \
		View/trova_elemento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

biblio.o: Model/biblio.cpp Model/biblio.h \
		Model/container.h \
		Model/smartptr.h \
		Model/libraryitem.h \
		Model/cd.h \
		Model/dvd.h \
		Model/film.h \
		Model/libro.h \
		Model/vhs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o biblio.o Model/biblio.cpp

cd.o: Model/cd.cpp Model/cd.h \
		Model/libraryitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cd.o Model/cd.cpp

dvd.o: Model/dvd.cpp Model/dvd.h \
		Model/film.h \
		Model/libraryitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dvd.o Model/dvd.cpp

film.o: Model/film.cpp Model/film.h \
		Model/libraryitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o film.o Model/film.cpp

libraryitem.o: Model/libraryitem.cpp Model/libraryitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libraryitem.o Model/libraryitem.cpp

libro.o: Model/libro.cpp Model/libro.h \
		Model/libraryitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libro.o Model/libro.cpp

smartptr.o: Model/smartptr.cpp Model/smartptr.h \
		Model/libraryitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smartptr.o Model/smartptr.cpp

vhs.o: Model/vhs.cpp Model/vhs.h \
		Model/film.h \
		Model/libraryitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vhs.o Model/vhs.cpp

gestione_cd.o: View/gestione_cd.cpp View/gestione_cd.h \
		Model/libraryitem.h \
		Model/cd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gestione_cd.o View/gestione_cd.cpp

gestione_dvd.o: View/gestione_dvd.cpp View/gestione_dvd.h \
		Model/libraryitem.h \
		Model/dvd.h \
		Model/film.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gestione_dvd.o View/gestione_dvd.cpp

gestione_libro.o: View/gestione_libro.cpp View/gestione_libro.h \
		Model/libraryitem.h \
		Model/libro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gestione_libro.o View/gestione_libro.cpp

gestione_vhs.o: View/gestione_vhs.cpp View/gestione_vhs.h \
		Model/libraryitem.h \
		Model/vhs.h \
		Model/film.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gestione_vhs.o View/gestione_vhs.cpp

mywidget.o: View/mywidget.cpp View/mywidget.h \
		Model/biblio.h \
		Model/container.h \
		Model/smartptr.h \
		Model/libraryitem.h \
		Model/cd.h \
		Model/dvd.h \
		Model/film.h \
		Model/libro.h \
		Model/vhs.h \
		View/gestione_libro.h \
		View/gestione_cd.h \
		View/gestione_dvd.h \
		View/gestione_vhs.h \
		View/trova_elemento.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget.o View/mywidget.cpp

trova_elemento.o: View/trova_elemento.cpp View/trova_elemento.h \
		Model/biblio.h \
		Model/container.h \
		Model/smartptr.h \
		Model/libraryitem.h \
		Model/cd.h \
		Model/dvd.h \
		Model/film.h \
		Model/libro.h \
		Model/vhs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trova_elemento.o View/trova_elemento.cpp

moc_gestione_cd.o: moc_gestione_cd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gestione_cd.o moc_gestione_cd.cpp

moc_gestione_dvd.o: moc_gestione_dvd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gestione_dvd.o moc_gestione_dvd.cpp

moc_gestione_libro.o: moc_gestione_libro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gestione_libro.o moc_gestione_libro.cpp

moc_gestione_vhs.o: moc_gestione_vhs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gestione_vhs.o moc_gestione_vhs.cpp

moc_mywidget.o: moc_mywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget.o moc_mywidget.cpp

moc_trova_elemento.o: moc_trova_elemento.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trova_elemento.o moc_trova_elemento.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

